# Generated by Django 3.1.4 on 2020-12-05 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=64, verbose_name='Квалификация')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(verbose_name='Ожидаемое вознаграждение')),
                ('education', tinymce.models.HTMLField(verbose_name='Content')),
                ('experience', tinymce.models.HTMLField(verbose_name='Content')),
                ('portfolio', models.CharField(max_length=64, verbose_name='Ссылка на портфолио')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.grade')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.specialty')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.status')),
            ],
        ),
    ]
