# Generated by Django 3.1.4 on 2020-12-05 14:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_grade_resume_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=tinymce.models.HTMLField(verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=tinymce.models.HTMLField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.grade', verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.specialty', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.status', verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='vacancyapplication',
            constraint=models.UniqueConstraint(fields=('vacancy', 'applicant'), name='one_vacancy_application'),
        ),
    ]
