# Generated by Django 3.1 on 2020-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20201202_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(upload_to='speciality_images'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
