# Generated by Django 3.1 on 2020-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20201202_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.FloatField(),
        ),
    ]
