# Generated by Django 3.1 on 2020-12-03 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0007_auto_20201202_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=64)),
                ('written_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('written_cover_letter', models.TextField()),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
    ]
