# Generated by Django 3.1 on 2020-12-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20201203_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy'),
        ),
    ]
