# Generated by Django 3.1 on 2020-12-04 11:54

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20201204_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=quilljs.fields.RichTextField(),
        ),
    ]
