# Generated by Django 3.1 on 2020-12-04 12:03

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20201204_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=editorjs_field.fields.EditorJSField(),
        ),
    ]
