# Generated by Django 3.1 on 2020-12-04 13:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_auto_20201204_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
